# Generated by Django 2.0.5 on 2018-05-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('mobile', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
